#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_FONTMAKER1                          101
#define IDR_MENU1                               102
#define IDD_ABOUT                               104
#define IDD_GRADIENTFILL                        106
#define IDD_SOLIDFILL                           108
#define IDD_OUTLINEPANEL                        110
#define IDD_PROGRESS                            112
#define IDC_BGPREVIEW                           1000
#define IDC_TEXTFILL                            1001
#define IDC_BITMAPPANEL                         1002
#define IDC_SPIN2                               1002
#define IDC_COMBOAA                             1003
#define IDC_EDITOUTLINEWIDTH                    1003
#define IDC_FONTCOMBO                           1004
#define IDC_PREVIEWVSCROLL                      1005
#define IDC_TXTOUTLINEPREVIEW                   1005
#define IDC_BOLD                                1006
#define IDC_COMIMGSIZE                          1007
#define IDC_ITALICS                             1008
#define IDABOUTOK                               1016
#define IDC_BGCOLOR                             1018
#define IDM_ABOUT1                              40000
#define IDM_SAVE1                               40001
#define IDM_EXIT1                               40002
#define IDC_TXTFILLPREVIEW                      40003
#define IDM_COPY_TO_CLIPBOARD1                  40003
#define IDC_OUTLINECOLOR                        40007
#define IDC_TXTSHADOWPREV                       40010
#define IDC_SHADOWCOLOR                         40012
#define IDC_CKSHADOW                            40016
#define IDC_RADSOLID                            40020
#define IDC_RADGRAD                             40021
#define IDC_FILLHOOK                            40022
#define IDC_GRADCOLOR                           40022
#define IDC_GRADANGLE                           40023
#define IDC_TXTGRADENDPREVIEW                   40024
#define IDC_CKDRAWBORDERS                       40025
#define IDC_GRADPREVIEW                         40026
#define IDC_RADOUTLINE                          40027
#define IDC_RADGLOW                             40029
#define IDC_RADNOOUTLINE                        40031
#define IDC_SPIN1                               40033
#define IDC_OUTLINEPANELANCHOR                  40035
#define IDC_EDITTEXTSIZE                        40036
#define CM_ZOOMOUT                              40040
#define CM_ZOOMIN                               40041
#define CM_ZOOMFULL                             40043
#define IDC_EDITSHADOWX                         40045
#define IDC_SPIN3                               40046
#define IDC_EDIT1                               40047
#define IDC_SPIN4                               40048
#define IDC_PROGRESS1                           40051
#define CM_FITWINDOW                            40053
#define IDC_RADFILLTEX                          40055
#define IDC_PREVIEWHSCROLL                      40056
